import { CalendarDays, User, Stethoscope } from "lucide-react";

export default function PrescriptionPreview({
  patient,
  diagnosis,
  medicines,
  notes,
  followUpDate,
}) {
  return (
    <div className="rounded-2xl bg-white p-8 shadow-lg border border-slate-200">

      <div className="border-b pb-6">

        <h1 className="text-3xl font-bold text-blue-700">
          Healthcare Appointment Manager
        </h1>

        <p className="text-slate-500 mt-2">
          Digital Prescription
        </p>

      </div>

      {/* Patient Information */}

      <div className="grid gap-6 mt-8 md:grid-cols-2">

        <div className="flex items-center gap-3">

          <User className="text-blue-600" />

          <div>

            <p className="text-sm text-slate-500">
              Patient
            </p>

            <h3 className="font-semibold">
              {patient?.fullName || "N/A"}
            </h3>

          </div>

        </div>

        <div className="flex items-center gap-3">

          <CalendarDays className="text-blue-600" />

          <div>

            <p className="text-sm text-slate-500">
              Follow-up
            </p>

            <h3 className="font-semibold">
              {followUpDate || "Not Required"}
            </h3>

          </div>

        </div>

      </div>

      {/* Diagnosis */}

      <div className="mt-8">

        <div className="flex items-center gap-2 mb-3">

          <Stethoscope
            className="text-green-600"
          />

          <h2 className="text-xl font-bold">
            Diagnosis
          </h2>

        </div>

        <p className="rounded-xl bg-slate-50 p-4">
          {diagnosis || "No diagnosis added."}
        </p>

      </div>

      {/* Medicines */}

      <div className="mt-8">

        <h2 className="text-xl font-bold mb-4">
          Medicines
        </h2>

        {medicines.length === 0 ? (
          <p className="text-slate-500">
            No medicines added.
          </p>
        ) : (
          <div className="overflow-x-auto">

            <table className="min-w-full border">

              <thead className="bg-slate-100">

                <tr>

                  <th className="p-3 text-left">
                    Medicine
                  </th>

                  <th className="p-3 text-left">
                    Dosage
                  </th>

                  <th className="p-3 text-left">
                    Frequency
                  </th>

                  <th className="p-3 text-left">
                    Duration
                  </th>

                  <th className="p-3 text-left">
                    Instructions
                  </th>

                </tr>

              </thead>

              <tbody>

                {medicines.map(
                  (medicine, index) => (
                    <tr
                      key={index}
                      className="border-t"
                    >
                      <td className="p-3">
                        {
                          medicine.medicineName
                        }
                      </td>

                      <td className="p-3">
                        {medicine.dosage}
                      </td>

                      <td className="p-3">
                        {
                          medicine.frequency
                        }
                      </td>

                      <td className="p-3">
                        {
                          medicine.duration
                        }
                      </td>

                      <td className="p-3">
                        {medicine.instructions ||
                          "-"}
                      </td>

                    </tr>
                  )
                )}

              </tbody>

            </table>

          </div>
        )}

      </div>

      {/* Notes */}

      <div className="mt-8">

        <h2 className="text-xl font-bold mb-3">
          Consultation Notes
        </h2>

        <div className="rounded-xl bg-slate-50 p-4">

          {notes || "No notes provided."}

        </div>

      </div>

      {/* Footer */}

      <div className="mt-10 border-t pt-6 flex justify-between">

        <div>

          <p className="font-semibold">
            Doctor Signature
          </p>

          <div className="mt-8 border-b w-48" />

        </div>

        <div className="text-right">

          <p className="text-sm text-slate-500">
            Generated by
          </p>

          <p className="font-semibold">
            Healthcare Appointment Manager
          </p>

        </div>

      </div>

    </div>
  );
}