import { useState } from "react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import { Sparkles } from "lucide-react";

import Button from "../common/Button";

import {
  bookAppointment,
} from "../../services/appointmentService";

import {
  generateSummary,
} from "../../services/aiService";

export default function AppointmentForm({
  selectedDoctor,
  selectedDate,
  selectedSlot,
}) {
  const [aiSummary, setAiSummary] =
    useState("");

  const [generatingAI, setGeneratingAI] =
    useState(false);

  const {
    register,
    handleSubmit,
    watch,
    reset,
    formState: {
      errors,
      isSubmitting,
    },
  } = useForm({
    defaultValues: {
      symptoms: "",
      meetingMode: "offline",
    },
  });

  /*
     Generate AI Summary
  */

  const handleGenerateAI =
    async () => {
      const symptoms =
        watch("symptoms");

      if (!symptoms) {
        return toast.error(
          "Please enter symptoms first."
        );
      }

      if (symptoms.length < 10) {
        return toast.error(
          "Please enter more detailed symptoms."
        );
      }

      try {
        setGeneratingAI(true);

        const response =
          await generateSummary(
            symptoms
          );

        setAiSummary(
          response.summary
        );

        toast.success(
          "AI summary generated."
        );
      } catch (error) {
        toast.error(
          error.response?.data
            ?.message ||
            "Unable to generate AI summary."
        );
      } finally {
        setGeneratingAI(false);
      }
    };

  /* 
     Book Appointment
  */

  const onSubmit = async (
    data
  ) => {
    if (!selectedDoctor) {
      return toast.error(
        "Please select a doctor."
      );
    }

    if (!selectedDate) {
      return toast.error(
        "Please select a date."
      );
    }

    if (!selectedSlot) {
      return toast.error(
        "Please select a time slot."
      );
    }

    try {
      await bookAppointment({
        doctor:
          selectedDoctor._id,

        appointmentDate:
          selectedDate.date,

        slot: {
          startTime:
            selectedSlot.startTime,

          endTime:
            selectedSlot.endTime,
        },

        symptoms:
          data.symptoms,

        meetingMode:
          data.meetingMode,

        aiSummary,
      });

      toast.success(
        "Appointment booked successfully!"
      );

      reset();

      setAiSummary("");
    } catch (error) {
      toast.error(
        error.response?.data
          ?.message ||
          "Booking failed."
      );
    }
  };
    return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="mt-10 rounded-2xl bg-white p-8 shadow-md"
    >
      <h2 className="mb-6 text-2xl font-bold text-slate-800">
        Appointment Details
      </h2>

      <div className="space-y-6">

        {/* Symptoms */}

        <div>

          <label className="mb-2 block font-medium">
            Symptoms
          </label>

          <textarea
            rows={5}
            placeholder="Describe your symptoms in detail..."
            className="w-full rounded-xl border p-4 focus:border-blue-500 focus:outline-none"
            {...register("symptoms", {
              required: "Symptoms are required",
              minLength: {
                value: 10,
                message:
                  "Please enter at least 10 characters.",
              },
            })}
          />

          {errors.symptoms && (
            <p className="mt-2 text-sm text-red-500">
              {errors.symptoms.message}
            </p>
          )}

        </div>

        {/* AI Button */}

        <Button
          type="button"
          variant="secondary"
          fullWidth
          onClick={handleGenerateAI}
          loading={generatingAI}
        >
          <div className="flex items-center justify-center gap-2">

            <Sparkles size={18} />

            {generatingAI
              ? "Generating AI Summary..."
              : "Generate AI Summary"}

          </div>
        </Button>

        {/* AI Summary */}

        {aiSummary && (

          <div className="rounded-xl border border-blue-200 bg-blue-50 p-5">

            <h3 className="mb-3 flex items-center gap-2 text-lg font-semibold text-blue-700">

              <Sparkles size={20} />

              AI Symptom Summary

            </h3>

            <div className="whitespace-pre-line text-slate-700">

              {aiSummary}

            </div>

            <p className="mt-4 text-xs text-slate-500">
              This summary is generated by AI and is intended
              to assist the doctor. It is not a medical diagnosis.
            </p>

          </div>

        )}

        {/* Meeting Mode */}

        <div>

          <label className="mb-2 block font-medium">
            Meeting Mode
          </label>

          <select
            className="w-full rounded-xl border p-3 focus:border-blue-500 focus:outline-none"
            {...register("meetingMode")}
          >

            <option value="offline">
              Offline Consultation
            </option>

            <option value="online">
              Online Consultation
            </option>

          </select>

        </div>

        {/* Appointment Summary */}

        <div className="rounded-xl bg-slate-100 p-5">

          <h3 className="mb-3 font-semibold">
            Appointment Summary
          </h3>

          <div className="space-y-2 text-sm">

            <p>
              <strong>Doctor:</strong>{" "}
              {selectedDoctor?.user?.fullName ||
                selectedDoctor?.name ||
                "Selected Doctor"}
            </p>

            <p>
              <strong>Date:</strong>{" "}
              {new Date(
                selectedDate.date
              ).toLocaleDateString()}
            </p>

            <p>
              <strong>Time:</strong>{" "}
              {selectedSlot.startTime} -{" "}
              {selectedSlot.endTime}
            </p>

          </div>

        </div>

        {/* Submit */}

        <Button
          type="submit"
          fullWidth
          loading={isSubmitting}
        >
          Confirm Appointment
        </Button>

      </div>

    </form>
  );
}
